services:
  db:
    image: postgres:15
    container_name: payments
    environment:
      POSTGRES_DB: payments  
      POSTGRES_USER: postgres       
      POSTGRES_PASSWORD: postgres     
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
